/**
 * Presets for NameMorph generator
 * Quick-start configurations that toggle specific modules on or off.
 */

export const PRESETS = {
  all: {
    id: 'all',
    name: 'All Enabled',
    icon: 'sparkles',
    description: 'Every transformation rule active for maximum variety',
    config: {
      enableLeet: true,
      enableLetterSwaps: true,
      enablePrefixes: true,
      enableSuffixes: true,
      enableVowels: true,
      enableExtensions: true,
      enableFraming: true,
      enableCasing: true,
      // Leet sub-options
      leetSubtle: true,
      leetFull: true,
      leetSymbols: true,
      // Letter swaps sub-options
      swapsPhonetic: true,
      swapsTypos: true,
      // Affix sub-options
      affixTech: true,
      affixGaming: true,
      affixSocial: true,
      affixDelimiters: true,
      // Vowel sub-options
      vowelsDrop: true,
      vowelsDouble: true,
      vowelsSwap: true
    }
  },
  brand: {
    id: 'brand',
    name: 'Startup & Brand',
    icon: 'rocket',
    description: 'Clean, SaaS/startup-ready names (.io, ify, vowel-drops, no leet numbers)',
    config: {
      enableLeet: false,
      enableLetterSwaps: true,
      enablePrefixes: true,
      enableSuffixes: true,
      enableVowels: true,
      enableExtensions: false,
      enableFraming: false,
      enableCasing: true,
      leetSubtle: false,
      leetFull: false,
      leetSymbols: false,
      swapsPhonetic: true,
      swapsTypos: false,
      affixTech: true,
      affixGaming: false,
      affixSocial: false,
      affixDelimiters: false,
      vowelsDrop: true,
      vowelsDouble: true,
      vowelsSwap: false
    }
  },
  gamer: {
    id: 'gamer',
    name: 'Gamer & Streamer',
    icon: 'gamepad',
    description: 'Leet speak, xX frames, _gg suffixes, and bold streamer tags',
    config: {
      enableLeet: true,
      enableLetterSwaps: true,
      enablePrefixes: true,
      enableSuffixes: true,
      enableVowels: false,
      enableExtensions: true,
      enableFraming: true,
      enableCasing: true,
      leetSubtle: true,
      leetFull: true,
      leetSymbols: true,
      swapsPhonetic: true,
      swapsTypos: true,
      affixTech: false,
      affixGaming: true,
      affixSocial: false,
      affixDelimiters: true,
      vowelsDrop: false,
      vowelsDouble: false,
      vowelsSwap: false
    }
  },
  swaps_only: {
    id: 'swaps_only',
    name: 'Letter Swaps Only',
    icon: 'repeat',
    description: 'Strictly alphabetical phonetic & typo substitutions without numbers or affixes',
    config: {
      enableLeet: false,
      enableLetterSwaps: true,
      enablePrefixes: false,
      enableSuffixes: false,
      enableVowels: false,
      enableExtensions: false,
      enableFraming: false,
      enableCasing: false,
      leetSubtle: false,
      leetFull: false,
      leetSymbols: false,
      swapsPhonetic: true,
      swapsTypos: true,
      affixTech: false,
      affixGaming: false,
      affixSocial: false,
      affixDelimiters: false,
      vowelsDrop: false,
      vowelsDouble: false,
      vowelsSwap: false
    }
  },
  leet_only: {
    id: 'leet_only',
    name: 'Leet Speak Only',
    icon: 'binary',
    description: 'Strictly numbers and symbol replacements (3, 4, 0, 5, 7, @, $) without affixes',
    config: {
      enableLeet: true,
      enableLetterSwaps: false,
      enablePrefixes: false,
      enableSuffixes: false,
      enableVowels: false,
      enableExtensions: false,
      enableFraming: false,
      enableCasing: false,
      leetSubtle: true,
      leetFull: true,
      leetSymbols: true,
      swapsPhonetic: false,
      swapsTypos: false,
      affixTech: false,
      affixGaming: false,
      affixSocial: false,
      affixDelimiters: false,
      vowelsDrop: false,
      vowelsDouble: false,
      vowelsSwap: false
    }
  },
  affixes_only: {
    id: 'affixes_only',
    name: 'Affixes Only',
    icon: 'plus',
    description: 'Prefixes & suffixes only (no letter or vowel alterations)',
    config: {
      enableLeet: false,
      enableLetterSwaps: false,
      enablePrefixes: true,
      enableSuffixes: true,
      enableVowels: false,
      enableExtensions: false,
      enableFraming: false,
      enableCasing: false,
      leetSubtle: false,
      leetFull: false,
      leetSymbols: false,
      swapsPhonetic: false,
      swapsTypos: false,
      affixTech: true,
      affixGaming: true,
      affixSocial: true,
      affixDelimiters: true,
      vowelsDrop: false,
      vowelsDouble: false,
      vowelsSwap: false
    }
  },
  vowels_only: {
    id: 'vowels_only',
    name: 'Disemvowel & Short',
    icon: 'scissors',
    description: 'Vowel drops (Tumblr/Flickr style) and vowel shifting only',
    config: {
      enableLeet: false,
      enableLetterSwaps: false,
      enablePrefixes: false,
      enableSuffixes: false,
      enableVowels: true,
      enableExtensions: false,
      enableFraming: false,
      enableCasing: false,
      leetSubtle: false,
      leetFull: false,
      leetSymbols: false,
      swapsPhonetic: false,
      swapsTypos: false,
      affixTech: false,
      affixGaming: false,
      affixSocial: false,
      affixDelimiters: false,
      vowelsDrop: true,
      vowelsDouble: true,
      vowelsSwap: true
    }
  },
  social_handles: {
    id: 'social_handles',
    name: 'Social Handles',
    icon: 'at-sign',
    description: 'Ready for Instagram, X, YouTube, TikTok handles (the_, official, real)',
    config: {
      enableLeet: false,
      enableLetterSwaps: false,
      enablePrefixes: true,
      enableSuffixes: true,
      enableVowels: false,
      enableExtensions: false,
      enableFraming: false,
      enableCasing: false,
      leetSubtle: false,
      leetFull: false,
      leetSymbols: false,
      swapsPhonetic: false,
      swapsTypos: false,
      affixTech: false,
      affixGaming: false,
      affixSocial: true,
      affixDelimiters: true,
      vowelsDrop: false,
      vowelsDouble: false,
      vowelsSwap: false
    }
  }
};
